### ISSUE TITLE
Wow!

### ISSUE THREAD

**Issue by edwinyzh** [sempare/sempare.boot.velocity.oss#1]
So far this is the most feature-rich template engine for Delphi/Pascal in the world as far as I know!

Being released today seems like a holiday gift for the community, thank you!

PS, I wish my XE4 can compile it :)

**Comment by darnocian** [comment]
Thanks. I had an itch... Sorry I haven’t got to look at older versions of Delphi yet.

I thought I’d start by just releasing what I had for Xmas. ;)

**Comment by edwinyzh** [comment]
It's a great thing on your side trying to make it as compatible with old Delphi as possible, I appreciate it and please keep this strategy!

For the compiling issue I think it can be fixed with some checking of delphi version and "uses" the units  you mentioned accordingly. I'll fix that and create a PR as soon as I can.

**Comment by edwinyzh** [comment]
BTW, your site (https://www.sempare.ltd/sempare.boot) is not working

**Comment by darnocian** [comment]
Yeah. I’m setting that page up over the holiday period. ;) you found the project too quickly without any advertising :)

**Comment by darnocian** [comment]
I've added some super short You Tube videos to illustrate usage. 
https://www.youtube.com/playlist?list=PLjjz4SuVScHreGKEInvrjPtLPMBU6l130

btw. I had a quick look at XE8 (which I could still install). ;) 
I spotted a few things getting the projects & tests to build on XE8:
- it didn't have TJSONBool and other things relating to System.JSON unit... 
- I used TTextWriter. I have an extension on that. I had a one line change, but need to just double check if it still works on 10.3.3.
- I got all projects except for Sempare.Boot.Template.Velocity.Design.Pkg to build.
- Unit tests build... but many are failing... I suspect the TEncoding, but would need to review.

**Comment by darnocian** [comment]
I've pushed. I made some adjustments so it works on XE8 now. I've added an .inc file that checks the compiler version for specific features. Let me know if it works for you on XE4... would be nice to know. I was surprised that the project group just worked when I opened it in XE8 having been saved with Rio.

**Comment by edwinyzh** [comment]
Hi darnocian,

As you requested, the following is the first error when compiling Sempare.Boot.Template.Velocity.Pkg
===
[dcc32 Fatal Error] Sempare.Boot.Template.Velocity.Context.pas(159): F1026 File not found: 'System.NetEncoding.dcu' (unit scope "System" indicates Win64, OSX32, Win32 only)

Sorry I couldn't help further at the moment due to project deadline here.

**Comment by darnocian** [comment]
I was checking the Embarcadero documentation. I suspect XE7 is the earliest.
http://docwiki.embarcadero.com/Libraries/XE7/en/System.NetEncoding.

**Comment by darnocian** [comment]
That was used to allow for HTML encoding of variables. It was an optional feature, so I've just removed the feature in this scenario for now.

**Comment by edwinyzh** [comment]
[You are right](http://docwiki.embarcadero.com/RADStudio/XE7/en/What%27s_New_in_Delphi_and_C++Builder_XE7#New_Unit_for_Web_Encoding_and_Decoding).

For checking Delphi versions with conditional defines, I suggest: https://github.com/novuslogic/DelphiVersions

For list of new language features added by each Delphi version, I suggest: https://stackoverflow.com/questions/8460037/list-of-delphi-language-features-and-version-in-which-they-were-introduced-depre

**Comment by edwinyzh** [comment]
BTW, are the demos shown on youtube available as sources ?

**Comment by darnocian** [comment]
Hi Edwin,

Yes. The demo tool is demo/VelocityDemo (which is also in the project group).

I just did a quick typing session. I probably should have saved them. ;)

Most of what I showed in the videos can be seen in the unit tests.

I always see people do demos by opening pre packaged projects and just run them - which never shows all the steps. Although the videos are short/fast, i wanted them to just give an idea as the tests/docs cover most things.

Regards,
Conrad

**Comment by edwinyzh** [comment]
Hello Conrad,

Thanks! BTW, Is your project inspired by the Original Java Velocity template engine?

**Comment by darnocian** [comment]
Hi Edwin.

I've used the java velocity in the past, and maybe it has had an influence. although I have not referenced it while writing this... and syntax is a bit different as they just use # as a start token. reflecting on it now, some of the api looks like java velocity and the templating looks like php. ;)

It might be a bad name (for people that are obsessed with brand name type stuff - will cross that bridge later if it becomes an issue). 

When I was actually looking for some templating. I saw some Mustache implementations, but I wanted a bit more functionality.

**Comment by edwinyzh** [comment]
I haven't used Java velocity nor Java, I just heard about it ;)

Yes, this is very powerful at first glance! It filled the blank of this field for the Delphi community! I just hope you don't use too much new features that's introduced  recently such as the inline var, so that I can actually need it I can make it at least compatible with my XE 4 :)

**Comment by darnocian** [comment]
I didn't use inline var. I'd like to use it more, but the wierd thing is that embarcadero didn't fix the IDE to support it - only the compiler does. So if you use inline vars, the IDE goes 'red' with errors, even though it is not. Even though compiling is generally fast, I prefer not to rely on it to highlight errors. By inline var is a really a nice feature as it means you don't necessarily have to worry about referencing units, declaring types,  variable scope relevance, etc depending on the situation... 

I only used the inline var to shorten some of the examples in the documentation. ;)

**Comment by edwinyzh** [comment]
I agree with you about inline var, it's quite a nice feature but the IDE support is lame, it's a pity.

And I appreciate your intention trying to keep some level of backward compatibility here!

**Comment by darnocian** [comment]
Hi Edwin, 

Just to confirm - it is building on XE4 now?

**Comment by edwinyzh** [comment]
@darnocian ,
Sorry, but not yet. The first two errors were:
```
[dcc32 Error] Sempare.Boot.Template.Velocity.Rtti.pas(109): E2003 Undeclared identifier: 'tkWideString'
[dcc32 Error] Sempare.Boot.Template.Velocity.Rtti.pas(109): E2003 Undeclared identifier: 'tkUnicodeString'
```

I fixed them by replacing them with tkWString and tkUString respectively, then I got:
```
[dcc32 Error] Sempare.Boot.Template.Velocity.Rtti.pas(756): E2003 Undeclared identifier: 'KeepContext'
[dcc32 Error] Sempare.Boot.Template.Velocity.Rtti.pas(774): E2003 Undeclared identifier: 'DropContext'
```

**Comment by darnocian** [comment]
It might be ok to drop the KeepContext/DropContext.

**Comment by sempare** [comment]
Hi Edwin,

Did you do any other tests?

Regards
Conrad
